"""field-level audit trail + electronic signatures

Rebuilds audit_event as a field-level, append-only trail (table, record id,
field, old/new value, actor, timestamp, reason) and adds the
electronic_signature table. audit_event holds no precious data (it is
regenerated by the seed), so it is dropped and recreated rather than migrated
column by column.

Revision ID: 0002_audit_esignature
Revises: e4ad6b849978
Create Date: 2026-07-26
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0002_audit_esignature"
down_revision: Union[str, None] = "e4ad6b849978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_NOW = sa.text("(CURRENT_TIMESTAMP)")


def upgrade() -> None:
    op.drop_table("audit_event")
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=80), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("insert", "update", name="audit_action", native_enum=False),
            nullable=False,
        ),
        sa.Column("field_name", sa.String(length=80), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "electronic_signature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=80), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("signer_name", sa.String(length=200), nullable=False),
        sa.Column("meaning", sa.String(length=200), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("electronic_signature")
    op.drop_table("audit_event")
    # Restore the original record-level audit_event schema.
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=80), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("create", "update", "void", name="audit_action", native_enum=False),
            nullable=False,
        ),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=_NOW, nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
