"""initial schema

Revision ID: e4ad6b849978
Revises: 
Create Date: 2026-07-26 16:17:41.674717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ad6b849978'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'void', name='audit_action', native_enum=False), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('part_type', sa.Enum('raw_material', 'component', 'finished_device', name='part_type', native_enum=False), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('bom_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_part_id', sa.Integer(), nullable=False),
    sa.Column('child_part_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['child_part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['parent_part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_part_id', 'position', name='uq_bom_line_parent_position')
    )
    op.create_table('supplier_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=80), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('received_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'supplier_name', 'lot_number', name='uq_supplier_lot_identity')
    )
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_process', 'completed', 'cancelled', name='work_order_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_number')
    )
    op.create_table('as_built_serial_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('certificate_of_conformance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_lot_id', sa.Integer(), nullable=False),
    sa.Column('document_reference', sa.String(length=300), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['supplier_lot_id'], ['supplier_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoming_inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_lot_id', sa.Integer(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disposition', sa.Enum('pending', 'accepted', 'accepted_with_deviation', 'rejected', name='inspection_disposition', native_enum=False), nullable=False),
    sa.Column('result_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['supplier_lot_id'], ['supplier_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('as_built_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_id', sa.Integer(), nullable=False),
    sa.Column('bom_line_id', sa.Integer(), nullable=True),
    sa.Column('consumed_supplier_lot_id', sa.Integer(), nullable=True),
    sa.Column('consumed_serial_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('(consumed_supplier_lot_id IS NOT NULL) <> (consumed_serial_id IS NOT NULL)', name='ck_as_built_component_exactly_one_source'),
    sa.ForeignKeyConstraint(['bom_line_id'], ['bom_line.id'], ),
    sa.ForeignKeyConstraint(['consumed_serial_id'], ['as_built_serial_record.id'], ),
    sa.ForeignKeyConstraint(['consumed_supplier_lot_id'], ['supplier_lot.id'], ),
    sa.ForeignKeyConstraint(['serial_id'], ['as_built_serial_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nonconformance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_lot_id', sa.Integer(), nullable=True),
    sa.Column('serial_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'use_as_is', 'rework', 'scrap', 'closed', name='nonconformance_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(length=120), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint('(supplier_lot_id IS NOT NULL) <> (serial_id IS NOT NULL)', name='ck_nonconformance_exactly_one_subject'),
    sa.ForeignKeyConstraint(['serial_id'], ['as_built_serial_record.id'], ),
    sa.ForeignKeyConstraint(['supplier_lot_id'], ['supplier_lot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nc_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonconformance')
    op.drop_table('as_built_component')
    op.drop_table('incoming_inspection')
    op.drop_table('certificate_of_conformance')
    op.drop_table('as_built_serial_record')
    op.drop_table('work_order')
    op.drop_table('supplier_lot')
    op.drop_table('bom_line')
    op.drop_table('part')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
